/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @author FusionCharts Technologies LLP
 @version fusioncharts/3.2.4-release.8565

 @attributions (infers respective third-party copyrights)
 Highcharts JS v2.1.9 (modified) <http://www.highcharts.com/license>
 SWFObject v2.2 (modified) <http://code.google.com/p/swfobject/>
 JSON v2 <http://www.JSON.org/js.html>
 jQuery 1.7.1 <http://jquery.com/>
 Firebug Lite 1.3.0 <http://getfirebug.com/firebuglite>
*/
(function(){if(!window.FusionCharts||!window.FusionCharts.version){var a={},i=a.modules={},j=a.interpreters={},g=Object.prototype.toString,c=/msie/i.test(navigator.userAgent)&&!window.opera,h=!!document.createElementNS&&!!document.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect,l=function(a,b){var d,c;if(b instanceof Array)for(d=0;d<b.length;d+=1)typeof b[d]!=="object"?a[d]=b[d]:(typeof a[d]!=="object"&&(a[d]=b[d]instanceof Array?[]:{}),l(a[d],b[d]));else for(d in b)typeof b[d]===
"object"?(c=g.call(b[d]),c==="[object Object]"?(typeof a[d]!=="object"&&(a[d]={}),l(a[d],b[d])):c==="[object Array]"?(a[d]instanceof Array||(a[d]=[]),l(a[d],b[d])):a[d]=b[d]):a[d]=b[d];return a};a.extend=function(a,b,d,c){var f;if(d&&a.prototype)a=a.prototype;if(c===!0)l(a,b);else for(f in b)a[f]=b[f];return a};a.uniqueId=function(){return"chartobject-"+(a.uniqueId.lastId+=1)};a.uniqueId.lastId=0;a.policies={options:{swfSrcPath:["swfSrcPath",void 0],product:["product","v3"],insertMode:["insertMode",
"replace"],safeMode:["safeMode",!0],overlayButton:["overlayButton",void 0],containerBackgroundColor:["backgroundColor",void 0],chartType:["type",void 0]},attributes:{lang:["lang","EN"],"class":["className","FusionCharts"],id:["id",void 0]},width:["width","400"],height:["height","300"],src:["swfUrl",""]};j.stat=["swfUrl","id","width","height","debugMode","registerWithJS","backgroundColor","scaleMode","lang","detectFlashVersion","autoInstallRedirect"];a.parsePolicies=function(c,b,d){var h,f,k;for(f in b)if(a.policies[f]instanceof
Array)k=d[b[f][0]],c[f]=k===void 0?b[f][1]:k;else for(h in typeof c[f]!=="object"&&(c[f]={}),b[f])k=d[b[f][h][0]],c[f][h]=k===void 0?b[f][h][1]:k};a.parseCommands=function(a,b,d){var c,f;typeof b==="string"&&(b=j[b]||[]);c=0;for(f=b.length;c<f;c++)a[b[c]]=d[c];return a};a.core=function(e){if(!(this instanceof a.core)){if(arguments.length===1&&e instanceof Array&&e[0]==="private"){if(i[e[1]])return;i[e[1]]={};e[3]instanceof Array&&(a.core.version[e[1]]=e[3]);return typeof e[2]==="function"?e[2].call(a,
i[e[1]]):a}if(arguments.length===1&&typeof e==="string")return a.core.items[e];a.raiseError&&a.raiseError(this,"25081840","run","",new SyntaxError('Use the "new" keyword while creating a new FusionCharts object'))}var b={};this.__state={};if(arguments.length===1&&typeof arguments[0]==="object")b=arguments[0];else if(a.parseCommands(b,j.stat,arguments),a.core.options.sensePreferredRenderer&&b.swfUrl&&b.swfUrl.match&&!b.swfUrl.match(/[^a-z0-9]+/ig))b.type=b.swfUrl;arguments.length>1&&typeof arguments[arguments.length-
1]==="object"&&(delete b[j.stat[arguments.length-1]],a.extend(b,arguments[arguments.length-1]));this.id=typeof b.id==="undefined"?this.id=a.uniqueId():b.id;this.args=b;if(a.core.items[this.id]instanceof a.core)a.raiseWarning(this,"06091847","param","",Error('A FusionChart oject with the specified id "'+this.id+'" already exists. Renaming it to '+(this.id=a.uniqueId())));if(b.type&&b.type.toString){if(!a.renderer.userSetDefault&&(c||h))b.renderer=b.renderer||"javascript";b.swfUrl=(a.core.options.swfSrcPath||
b.swfSrcPath||a.core.options.scriptBaseUri).replace(/\/\s*$/g,"")+"/"+b.type.replace(/\.swf\s*?$/ig,"")+".swf"}a.parsePolicies(this,a.policies,b);this.attributes.id=this.id;this.resizeTo(b.width,b.height,!0);a.raiseEvent("BeforeInitialize",b,this);a.core.items[this.id]=this;a.raiseEvent("Initialized",b,this);return this};a.core.prototype={};a.core.prototype.constructor=a.core;a.extend(a.core,{id:"FusionCharts",version:[3,2,4,"release",8565],items:{},options:{sensePreferredRenderer:!0},getObjectReference:function(c){return a.core.items[c].ref}},
!1);window.FusionCharts=a.core;window.FusionMaps&&window.FusionMaps.legacy?a.core(["private","modules.core.geo",window.FusionMaps.legacy,window.FusionMaps.version]):!/loaded|complete/.test(document.readyState)&&!document.loaded&&function(){function c(){if(!arguments.callee.done)arguments.callee.done=!0,d&&clearInterval(d),window.FusionMaps&&window.FusionMaps.legacy&&a.core(["private","modules.core.geo",window.FusionMaps.legacy,window.FusionMaps.version]),window.FusionMaps=a.core}document.addEventListener?
document.addEventListener("DOMContentLoaded",c,!1):document.attachEvent&&window.attachEvent("onLoad",c);if(/msie/i.test(navigator.userAgent)&&!window.opera)try{document.write("<script id=__ie_onload defer src=javascript:void(0)><\/script>"),document.getElementById("__ie_onload").onreadystatechange=function(){this.readyState=="complete"&&c()}}catch(b){}if(/WebKit/i.test(navigator.userAgent))var d=setInterval(function(){/loaded|complete/.test(document.readyState)&&c()},10);window.onload=function(a){return function(){c();
a&&a.call&&a.call(window)}}(window.onload)}();window.FusionMaps=a.core}})();
(function(){var a=FusionCharts(["private","EventManager"]);if(a!==void 0){window.FusionChartsEvents={BeforeInitialize:"beforeinitialize",Initialized:"initialized",Loaded:"loaded",BeforeRender:"beforerender",Rendered:"rendered",DataLoadRequested:"dataloadrequested",DataLoadRequestCancelled:"dataloadrequestcancelled",DataLoadRequestCompleted:"dataloadrequestcompleted",BeforeDataUpdate:"beforedataupdate",DataUpdateCancelled:"dataupdatecancelled",DataUpdated:"dataupdated",DataLoadCancelled:"dataloadcancelled",
DataLoaded:"dataloaded",DataLoadError:"dataloaderror",NoDataToDisplay:"nodatatodisplay",DataXMLInvalid:"dataxmlinvalid",InvalidDataError:"invaliddataerror",DrawComplete:"drawcomplete",Resized:"resized",BeforeDispose:"beforedispose",Disposed:"disposed"};var i=function(a,h,l,e){try{a[0].call(h,l,e||{})}catch(b){setTimeout(function(){throw b;},0)}},j=function(c,h,l){if(c instanceof Array)for(var e=0,b;e<c.length;e+=1){if(c[e][1]===h.sender||c[e][1]===void 0)if(b=c[e][1]===h.sender?h.sender:a.core,i(c[e],
b,h,l),h.detached===!0)c.splice(e,1),e-=1,h.detached=!1;if(h.cancelled===!0)break}},g={unpropagator:function(){return(this.cancelled=!0)===!1},detacher:function(){return(this.detached=!0)===!1},undefaulter:function(){return(this.prevented=!0)===!1},listeners:{},lastEventId:0,addListener:function(c,h,l){if(c instanceof Array)for(var e=0;e<c.length;e+=1)g.addListener(c[e],h,l);else typeof c!=="string"?a.raiseError(l||a.core,"03091549","param","::EventTarget.addListener",Error("Unspecified Event Type")):
typeof h!=="function"?a.raiseError(l||a.core,"03091550","param","::EventTarget.addListener",Error("Invalid Event Listener")):(c=c.toLowerCase(),g.listeners[c]instanceof Array||(g.listeners[c]=[]),g.listeners[c].push([h,l]))},removeListener:function(c,h,l){var e;if(typeof h!=="function")a.raiseError(l||a.core,"03091560","param","::EventTarget.removeListener",Error("Invalid Event Listener"));else if(c instanceof Array)for(e=0;e<c.length;e+=1)g.removeListener(c[e],h,l);else if(typeof c!=="string")a.raiseError(l||
a.core,"03091559","param","::EventTarget.removeListener",Error("Unspecified Event Type"));else if(c=c.toLowerCase(),c=g.listeners[c],c instanceof Array)for(e=0;e<c.length;e+=1)c[e][0]===h&&c[e][1]===l&&(c.splice(e,1),e-=1)},triggerEvent:function(c,h,l,e,b){if(typeof c!=="string")a.raiseError(h,"03091602","param","::EventTarget.dispatchEvent",Error("Invalid Event Type"));else{c=c.toLowerCase();h={eventType:c,eventId:g.lastEventId+=1,sender:h||Error("Orphan Event"),cancel:!1,stopPropagation:this.unpropagator,
prevented:!1,preventDefault:this.undefaulter,detached:!1,detachHandler:this.detacher};if(e)h.originalEvent=e;j(g.listeners[c],h,l);j(g.listeners["*"],h,l);b&&h.prevented===!1&&i(b,h.sender,h,l);return!0}}};a.raiseEvent=function(a,h,l,e,b){return g.triggerEvent(a,l,h,e,b)};a.addEventListener=function(a,h){return g.addListener(a,h)};a.removeEventListener=function(a,h){return g.removeListener(a,h)};a.extend(a.core,{addEventListener:a.addEventListener,removeEventListener:a.removeEventListener},!1);a.extend(a.core,
{addEventListener:function(a,h){return g.addListener(a,h,this)},removeEventListener:function(a,h){return g.removeListener(a,h,this)}},!0);a.addEventListener("BeforeDispose",function(a){var h,l;for(h in g.listeners)for(l=0;l<g.listeners[h].length;l+=1)g.listeners[h][l][1]===a.sender&&g.listeners[h].splice(l,1)})}})();
(function(){var a=FusionCharts(["private","ErrorHandler"]);if(a!==void 0){var i={type:"TypeException",range:"ValueRangeException",impl:"NotImplementedException",param:"ParameterException",run:"RuntimeException",comp:"DesignTimeError",undefined:"UnspecifiedException"},j=function(c,h,l,e,b,d){var t="#"+h+" "+(c?c.id:"unknown-source")+e+" "+d+" >> ";b instanceof Error?(b.name=i[l],b.module="FusionCharts"+e,b.level=d,b.message=t+b.message,t=b.message,window.setTimeout(function(){throw b;},0)):t+=b;h=
{id:h,nature:i[l],source:"FusionCharts"+e,message:t};a.raiseEvent(d,h,c);if(typeof window["FC_"+d]==="function")window["FC_"+d](h)};a.raiseError=function(a,h,l,e,b){j(a,h,l,e,b,"Error")};a.raiseWarning=function(a,h,l,e,b){j(a,h,l,e,b,"Warning")};var g={outputHelpers:{text:function(a,h){g.outputTo("#"+a.eventId+" ["+(a.sender.id||a.sender).toString()+'] fired "'+a.eventType+'" event. '+(a.eventType==="error"||a.eventType==="warning"?h.message:""))},event:function(a,h){this.outputTo(a,h)},verbose:function(a,
h){g.outputTo(a.eventId,a.sender.id,a.eventType,h)}},outputHandler:function(c,h){typeof g.outputTo!=="function"?a.core.debugMode.outputFailed=!0:(a.core.debugMode.outputFailed=!1,g.currentOutputHelper(c,h))},currentOutputHelper:void 0,outputTo:void 0,enabled:!1};g.currentOutputHelper=g.outputHelpers.text;a.extend(a.core,{debugMode:{syncStateWithCharts:!0,outputFormat:function(a){if(a&&typeof a.toLowerCase==="function"&&typeof g.outputHelpers[a=a.toLowerCase()]==="function")return g.currentOutputHelper=
g.outputHelpers[a],!0;return!1},outputTo:function(c){typeof c==="function"?g.outputTo=c:c===null&&(a.core.debugMode.enabled(!1),delete g.outputTo)},enabled:function(c,h,l){var e;if(typeof c==="object"&&arguments.length===1)e=c,c=e.state,h=e.outputTo,l=e.outputFormat;if(typeof c==="function"){if(typeof h==="string"&&(arguments.length===2||e))l=h;h=c;c=!0}if(typeof c==="boolean"&&c!==g.enabled)a.core[(g.enabled=c)?"addEventListener":"removeEventListener"]("*",g.outputHandler);if(typeof h==="function")g.outputTo=
h;a.core.debugMode.outputFormat(l);return g.enabled},_enableFirebugLite:function(){window.console&&window.console.firebug?a.core.debugMode.enabled(console.log,"verbose"):a.loadScript("firebug-lite.js",function(){a.core.debugMode.enabled(console.log,"verbose")},"{ startOpened: true }")}}},!1)}})();
(function(){var a=FusionCharts(["private","modules.mantle.ajax"]);if(a){var i=window,j=parseFloat(navigator.appVersion.split("MSIE")[1]),g=j>=5.5&&j<=7?!0:!1,c=i.location.protocol==="file:",h=i.ActiveXObject,l=(!h||!c)&&i.XMLHttpRequest,e={objects:0,xhr:0,requests:0,success:0,failure:0,idle:0},b=function(){var a;if(l)return b=function(){e.xhr++;return new l},b();try{a=new h("Msxml2.XMLHTTP"),b=function(){e.xhr++;return new h("Msxml2.XMLHTTP")}}catch(c){try{a=new h("Microsoft.XMLHTTP"),b=function(){e.xhr++;
return new h("Microsoft.XMLHTTP")}}catch(f){a=!1}}return a},i=a.ajax=function(a,b){this.onSuccess=a;this.onError=b;this.open=!1;e.objects++;e.idle++};i.stats=function(b){return b?e[b]:a.extend({},e)};i.prototype.headers={"If-Modified-Since":"Sat, 29 Oct 1994 19:43:31 GMT","X-Requested-With":"XMLHttpRequest","X-Requested-By":"FusionCharts",Accept:"text/plain, */*"};i.prototype.get=function(d,h){var f=this,k=f.xmlhttp,s=f.headers,p=f.onError,m=f.onSuccess,n;if(!k||g)k=b(),f.xmlhttp=k;k.onreadystatechange=
function(){try{if(k.readyState===4)!k.status&&c||k.status>=200&&k.status<300||k.status===304||k.status===1223||k.status===0?(m&&m(k.responseText,f,h,d),e.success++):p&&(p(Error("XmlHttprequest Error"),f,h,d),e.failure++),e.idle--,f.open=!1}catch(a){p&&p(a,f,h,d),e.failure++}};try{k.overrideMimeType&&k.overrideMimeType("text/plain");k.open("GET",d,!0);for(n in s)k.setRequestHeader(n,s[n]);k.send(null);e.requests++;e.idle++;f.open=!0}catch(l){a.raiseError(a.core,"1110111515A","run","XmlHttprequest Error",
l.message)}return k};i.prototype.abort=function(){var a=this.xmlhttp;this.open=!1;return a&&typeof a.abort==="function"&&a.readyState&&a.readyState!==0&&a.abort()};i.prototype.dispose=function(){this.open&&this.abort();delete this.onError;delete this.onSuccess;delete this.xmlhttp;delete this.open;e.objects--;return null}}})();
(function(){var a=FusionCharts(["private","modules.mantle.runtime;1.1"]);if(a!==void 0){var i=/(^|[\/\\])(fusioncharts\.js|fusioncharts\.debug\.js|fusioncharts\.core\.js|fusioncharts\.min\.js)([\?#].*)?$/ig;a.getScriptBaseUri=function(a){var b=document.getElementsByTagName("script"),f=b.length,d,k;for(k=0;k<f;k+=1)if(d=b[k].getAttribute("src"),!(d===void 0||d===null||d.match(a)===null))return d.replace(a,"$1")};a.core.options.scriptBaseUri=function(){var b=a.getScriptBaseUri(i);if(b===void 0)return a.raiseError(FusionCharts,
"1603111624","run",">GenericRuntime~scriptBaseUri","Unable to locate FusionCharts script source location (URL)."),"";return b}();var j=/[\\\"<>;&]/,g=/^[^\S]*?(sf|f|ht)(tp|tps):\/\//i,c=FusionChartsEvents.ExternalResourceLoad="externalresourceload",h={},l={},e={},b={};a.isXSSSafe=function(a,b){if(b&&g.exec(a)!==null)return!1;return j.exec(a)===null};a.loadScript=function(f,d,m,k,g){if(!f)return!1;var t=d&&d.success||d,j=d&&d.failure,i,w={type:"script",success:!1},v=function(){b[i]=clearTimeout(b[i]);
w.success?t&&t(f,i):j&&j(f,i);a.raiseEvent(c,w,a.core)},g=g?"":a.core.options.scriptBaseUri;i=g+f;a.isXSSSafe(i,!1)||(i=typeof window.encodeURIComponent==="function"?window.encodeURIComponent(i):window.escape(i));w.path=g;w.src=i;w.file=f;if(e[i]===!0&&k)return w.success=!0,w.notReloaded=!0,typeof d==="function"&&(d(),a.raiseEvent(c,w,a.core)),!0;if(h[i]&&k)return!1;h[i]=!0;l[i]&&l[i].parentNode&&l[i].parentNode.removeChild(l[i]);d=l[i]=document.createElement("script");d.type="text/javascript";d.src=
i;m&&(d.innerHTML=m);if(typeof t==="function")e[i]=!1,b[i]=clearTimeout(b[i]),d.onload=function(){e[i]=!0;w.success=!0;v()},d.onerror=function(){e[i]=!1;h[i]=!1;v()},d.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded")e[i]=!0,w.success=!0,v()};document.getElementsByTagName("head")[0].appendChild(d);typeof j==="function"&&(b[i]=setTimeout(function(){e[i]||v()},a.core.options.html5ResourceLoadTimeout||15E3));return!0};a.capitalizeString=function(a,b){return a?
a.replace(b?/(^|\s)([a-z])/g:/(^|\s)([a-z])/,function(a,b,f){return b+f.toUpperCase()}):a};var d=a.purgeDOM=function(a){var b=a.attributes,f,k;if(b)for(f=b.length-1;f>=0;f-=1)k=b[f].name,typeof a[k]==="function"&&(a[k]=null);if(b=a.childNodes){b=b.length;for(f=0;f<b;f+=1)d(a.childNodes[f])}},t=function(a,b,f){for(var d in a){var k;if(a[d]instanceof Array)b[a[d][0]]=f[d];else for(k in a[d])b[a[d][k][0]]=f[d][k]}},f=/[^\%\d]*$/ig,k=/^(FusionCharts|FusionWidgets|FusionMaps)/;a.extend(a.core,{dispose:function(){a.raiseEvent("BeforeDispose",
{},this);a.renderer.dispose(this);delete a.core.items[this.id];a.raiseEvent("Disposed",{},this);for(var b in this)delete this[b]},clone:function(b,f){var d=typeof b,k={},c=a.extend({},this.args,!1,!1);t(a.policies,c,this);t(a.renderer.getRendererPolicy(this.options.renderer),c,this);delete c.id;delete c.animate;delete c.stallLoad;k.link=c.link;c=a.extend({},c,!1,!1);c.link=k.link;switch(d){case "object":a.extend(c,b);break;case "boolean":f=b}return f?c:new a.core(c)},isActive:function(){if(!this.ref||
document.getElementById(this.id)!==this.ref||typeof this.ref.signature!=="function")return!1;try{return k.test(this.ref.signature())}catch(a){return!1}},resizeTo:function(b,d,k){var c={width:b,height:d};if(typeof b==="object")c.width=b.width,c.height=b.height,k=d;if(c.width&&typeof c.width.toString==="function")this.width=c.width.toString().replace(f,"");if(c.height&&typeof c.height.toString==="function")this.height=c.height.toString().replace(f,"");k!==!0&&a.renderer.resize(this,c)},chartType:function(a){var b=
this.src,f;if(typeof a==="string")this.src=a,this.isActive()&&this.render();return(f=(f=b.substring(b.indexOf(".swf"),0))?f:b).substring(f.lastIndexOf("/")+1).toLowerCase().replace(/^fcmap_/i,"")}},!0);window.getChartFromId=window.getMapFromId=function(b){a.raiseWarning(this,"11133001041","run","GenericRuntime~getObjectFromId()",'Use of deprecated getChartFromId() or getMapFromId(). Replace with "FusionCharts()" or FusionCharts.items[].');return a.core.items[b]instanceof a.core?a.core.items[b].ref:
window.swfobject.getObjectById(b)}}})();
(function(){var a=FusionCharts(["private","RendererManager"]);if(a!==void 0){a.policies.options.containerElementId=["renderAt",void 0];a.policies.options.renderer=["renderer",void 0];a.normalizeCSSDimension=function(a,d,c){var a=a===void 0?c.offsetWidth:a,d=d===void 0?c.offsetHeight:d,f;c.style.width=a=a.toString?a.toString():"0";c.style.height=d=d.toString?d.toString():"0";if(a.match(/^\s*\d*\.?\d*\%\s*$/)&&!a.match(/^\s*0\%\s*$/)&&c.offsetWidth===0)for(f=c;f=f.offsetParent;)if(f.offsetWidth>0){a=
(f.offsetWidth*parseFloat(a.match(/\d*/)[0])/100).toString();break}if(d.match(/^\s*\d*\.?\d*\%\s*$/)&&!d.match(/^\s*0\%\s*$/)&&c.offsetHeight<=20)for(f=c;f=f.offsetParent;)if(f.offsetHeight>0){d=(f.offsetHeight*parseFloat(d.match(/\d*/)[0])/100).toString();break}f={width:a.replace?a.replace(/^\s*(\d*\.?\d*)\s*$/ig,"$1px"):a,height:d.replace?d.replace(/^\s*(\d*\.?\d*)\s*$/ig,"$1px"):d};c.style.width=f.width;c.style.height=f.height;return f};var i=function(){a.raiseError(this,"25081845","run","::RendererManager",
Error("No active renderer"))},j={undefined:{render:i,remove:i,update:i,resize:i,config:i,policies:{}}},g={},c=a.renderer={register:function(b,d){if(!b||typeof b.toString!=="function")throw"#03091436 ~renderer.register() Invalid value for renderer name.";b=b.toString().toLowerCase();if(j[b]!==void 0)return a.raiseError(a.core,"03091438","param","::RendererManager>register",'Duplicate renderer name specified in "name"'),!1;j[b]=d;return!0},userSetDefault:!1,setDefault:function(b){if(!b||typeof b.toString!==
"function")return a.raiseError(a.core,"25081731","param","::RendererManager>setDefault",'Invalid renderer name specified in "name"'),!1;if(j[b=b.toString().toLowerCase()]===void 0)return a.raiseError(a.core,"25081733","range","::RendererManager>setDefault","The specified renderer does not exist."),!1;this.userSetDefault=!1;a.policies.options.renderer=["renderer",b];return!0},notifyRender:function(b){var d=a.core.items[b&&b.id];(!d||b.success===!1&&!b.silent)&&a.raiseError(a.core.items[b.id],"25081850",
"run","::RendererManager",Error("There was an error rendering the chart. Enable FusionCharts JS debugMode for more information."));if(d.ref=b.ref)if(b.ref.FusionCharts=a.core.items[b.id],d.options.containerBackgroundColor)b.ref.style&&(b.ref.style.backgroundColor=d.options.containerBackgroundColor);a.raiseEvent("internal.DOMElementCreated",b,d)},protectedMethods:{options:!0,attributes:!0,src:!0,ref:!0,constructor:!0,signature:!0,link:!0},getRenderer:function(a){return j[a]},getRendererPolicy:function(a){a=
j[a].policies;return typeof a==="object"?a:{}},currentRendererName:function(){return a.policies.options.renderer[1]},update:function(a){g[a.id].update.apply(a,Array.prototype.slice.call(arguments,1))},render:function(a){g[a.id].render.apply(a,Array.prototype.slice.call(arguments,1))},remove:function(a){g[a.id].remove.apply(a,Array.prototype.slice.call(arguments,1))},resize:function(a){g[a.id].resize.apply(a,Array.prototype.slice.call(arguments,1))},config:function(a){g[a.id].config.apply(a,Array.prototype.slice.call(arguments,
1))},dispose:function(a){g[a.id].dispose.apply(a,Array.prototype.slice.call(arguments,1))}},h=function(b){return function(){if(this.ref===void 0||this.ref===null||typeof this.ref[b]!=="function")a.raiseError(this,"25081617","run","~"+b+"()","ExternalInterface call failed. Check whether chart has been rendered.");else return this.ref[b].apply(this.ref,arguments)}};a.addEventListener("BeforeInitialize",function(b){var b=b.sender,d;if(typeof b.options.renderer==="string"&&j[b.options.renderer.toLowerCase()]===
void 0)b.options.renderer=a.policies.options.renderer[1];b.options.renderer=b.options.renderer.toLowerCase();g[b.id]=j[b.options.renderer];if(g[b.id].initialized!==!0&&typeof g[b.id].init==="function")g[b.id].init(),g[b.id].initialized=!0;a.parsePolicies(b,g[b.id].policies||{},b.args);for(var c in g[b.id].prototype)b[c]=g[b.id].prototype[c];for(d in g[b.id].events)b.addEventListener(d,g[b.id].events[d])});a.addEventListener("Loaded",function(b){var d=b.sender,b=b.sender.ref;d instanceof a.core&&delete d.__state.rendering;
if(!(b===void 0||b===null||typeof b.getExternalInterfaceMethods!=="function")){var c;try{c=b.getExternalInterfaceMethods(),c=typeof c==="string"?c.split(","):[]}catch(f){c=[],a.raiseError(d,"13111126041","run","RendererManager^Loaded",Error("Error while retrieving data from the chart-object."+(f.message&&f.message.indexOf("NPObject")>=0?" Possible cross-domain security restriction.":"")))}for(b=0;b<c.length;b+=1)d[c[b]]===void 0&&(d[c[b]]=h(c[b]))}});var l=function(a,d){if(typeof a[d]==="function")return function(){return a[d].apply(a,
arguments)};return a[d]};a.addEventListener("loaded",function(b){var d=b.sender;if(d.ref){var c=a.renderer.protectedMethods,f=a.renderer.getRenderer(d.options.renderer).protectedMethods,k;for(k in b.sender)if(f&&!c[k]&&!(f[k]||d.ref[k]!==void 0))try{d.ref[k]=l(b.sender,k)}catch(e){}}});var e=function(a,d){var c=document.getElementById(a),f=d.getAttribute("id");if(c===null)return!1;if(a===f)return!0;for(var f=d.getElementsByTagName("*"),k=0;k<f.length;k+=1)if(f[k]===c)return!1;return!0};a.extend(a.core,
{render:function(b){var d,c;((d=window[this.id])&&d.FusionCharts&&d.FusionCharts===this||(d=this.ref)&&d.FusionCharts&&d.FusionCharts===this)&&a.renderer.dispose(this);window[this.id]!==void 0&&a.raiseError(this,"25081843","comp",".render",Error("#25081843:IECompatibility() Chart Id is same as a JavaScript variable name. Variable naming error. Please use unique name for chart JS variable, chart-id and container id."));c=this.options.insertMode.toLowerCase()||"replace";if(b===void 0)b=this.options.containerElementId;
typeof b==="string"&&(b=document.getElementById(b));if(b===void 0||b===null)return a.raiseError(this,"03091456","run",".render()",Error("Unable to find the container DOM element.")),this;if(e(this.id,b))return a.raiseError(this,"05102109","run",".render()",Error("A duplicate object already exists with the specific Id: "+this.id)),this;d=document.createElement(this.options.containerElementType||"span");d.setAttribute("id",this.id);if(c!=="append"&&c!=="prepend")for(;b.hasChildNodes();)b.removeChild(b.firstChild);
c==="prepend"&&b.firstChild?b.insertBefore(d,b.firstChild):b.appendChild(d);this.options.containerElement=b;this.options.containerElementId=b.id;if(c=d.style)c.lineHeight="100%",c.display="inline-block",c.zoom="1",c["*DISPLAY"]="inline";a.normalizeCSSDimension(this.width,this.height,d);this.__state.rendering=!0;a.raiseEvent("BeforeRender",{container:b,width:this.width,height:this.height,renderer:this.options.renderer},this);a.renderer.render(this,d,a.renderer.notifyRender);return this},remove:function(){a.renderer.remove(this);
return this},configure:function(b,d){var c;b&&(typeof b==="string"?(c={},c[b]=d):c=b,a.renderer.config(this,c))}},!0);a.extend(a.core,{setCurrentRenderer:function(){var a=c.setDefault.apply(c,arguments);c.userSetDefault=!0;return a},getCurrentRenderer:function(){return c.currentRendererName.apply(c,arguments)},render:function(){var b=["swfUrl","id","width","height","renderAt","dataSource","dataFormat"],d={},c;if(arguments[0]instanceof a.core)return arguments[0].render(),arguments[0];for(c=0;c<arguments.length&&
c<b.length;c+=1)d[b[c]]=arguments[c];typeof arguments[arguments.length-1]==="object"&&(delete d[b[c-1]],a.extend(d,arguments[arguments.length-1]));if(d.dataFormat===void 0)d.dataFormat=FusionChartsDataFormats.XMLURL;return(new a.core(d)).render()}},!1)}})();
(function(){var a=FusionCharts(["private","DataHandlerManager"]);if(a!==void 0){window.FusionChartsDataFormats={};var i=a.transcoders={},j={},g={},c=/url$/i,h=function(b,d,c,f){var k=!1,e=c.obj,h=c.format,c=c.silent;a.raiseEvent("DataLoadRequestCompleted",{source:"XmlHttpRequest",url:f,data:b,dataFormat:h,cancelDataLoad:function(){k=!0;d.abort();this.cancelDataLoad=function(){return!1};return!0},xmlHttpRequestObject:d.xhr},e);k!==!0?e.setChartData(b,h,c):a.raiseEvent("DataLoadCancelled",{source:"XmlHttpRequest",
url:f,dataFormat:h,xmlHttpRequestObject:d.xhr},e)},l=function(b,d,c,f){c=c.obj;b={source:"XmlHttpRequest",url:f,xmlHttpRequestObject:d.xhr,error:b,httpStatus:d.xhr&&d.xhr.status?d.xhr.status:-1};a.raiseEvent("DataLoadError",b,c);typeof window.FC_DataLoadError==="function"&&window.FC_DataLoadError(c.id,b)};a.policies.options.dataSource=["dataSource",void 0];a.policies.options.dataFormat=["dataFormat",void 0];a.policies.options.dataConfiguration=["dataConfiguration",void 0];a.policies.options.showDataLoadingMessage=
["showDataLoadingMessage",!0];a.addDataHandler=function(b,d){if(typeof b!=="string"||i[b.toLowerCase()]!==void 0)a.raiseError(a.core,"03091606","param","::DataManager.addDataHandler",Error("Invalid Data Handler Name"));else{var c={},f=b.toLowerCase();i[f]=d;d.name=b;c["set"+b+"Url"]=function(a){return this.setChartDataUrl(a,b)};c["set"+b+"Data"]=function(a,f){return this.setChartData(a,b,!1,f)};c["get"+b+"Data"]=function(){return this.getChartData(b)};window.FusionChartsDataFormats[b]=f;window.FusionChartsDataFormats[b+
"URL"]=f+"URL";a.extend(a.core,c,!0)}};a.addEventListener("BeforeInitialize",function(a){a=a.sender;j[a.id]="";g[a.id]={};if(a.options.dataSource!==void 0&&typeof a.options.dataFormat==="string")a.__state.dataSetDuringConstruction=!0,a.setChartData(a.options.dataSource,a.options.dataFormat)});a.addEventListener("BeforeDispose",function(a){var c=a.sender;delete j[a.sender.id];delete g[a.sender.id];c&&c.__state&&c.__state.dhmXhrObj&&c.__state.dhmXhrObj.abort()});a.extend(a.core,{setChartDataUrl:function(b,
d,e){if(d===void 0||d===null||typeof d.toString!=="function")a.raiseError(a.core,"03091609","param",".setChartDataUrl",Error("Invalid Data Format"));else{var d=d.toString().toLowerCase(),f,k=this,s=k.options&&k.options.renderer==="flash"&&k.options.useLegacyXMLTransport||!1;c.test(d)?f=d.slice(0,-3):(f=d,d+="url");a.raiseEvent("DataLoadRequested",{source:"XmlHttpRequest",url:b,dataFormat:f,cancelDataLoadRequest:function(){s=!0;a.raiseEvent("DataLoadRequestCancelled",{source:"XmlHttpRequest",url:b,
dataFormat:f},k);try{this.__state&&this.__state.dhmXhrObj&&this.__state.dhmXhrObj.abort()}catch(c){}this.cancelDataLoadRequest=function(){return!1};return!0}},k);if(s){if(this.__state&&this.__state.dhmXhrObj)try{this.__state.dhmXhrObj.abort()}catch(g){}}else{this.options.dataSource=b;if(!this.__state.dhmXhrObj)this.__state.dhmXhrObj=new a.ajax(h,l);this.__state.dhmXhrObj.get(typeof window.decodeURIComponent==="function"?window.decodeURIComponent(b):window.unescape(b),{obj:this,format:f,silent:e})}}},
setChartData:function(b,d,e){if(d===void 0||d===null||typeof d.toString!=="function")a.raiseError(a.core,"03091610","param",".setChartData",Error("Invalid Data Format"));else{var d=d.toString().toLowerCase(),f;if(c.test(d))this.setChartDataUrl(b,d,e);else{this.options.dataSource=b;f=d;this.options.dataFormat=d;var d=i[f],k=!1;if(typeof d==="undefined")a.raiseError(a.core,"03091611","param",".setChartData",Error("Data Format not recognized"));else if(d=d.encode(b,this,this.options.dataConfiguration)||
{},d.format=d.dataFormat=f,d.dataSource=b,d.cancelDataUpdate=function(){k=!0;this.cancelDataUpdate=function(){return!1};return!0},a.raiseEvent("BeforeDataUpdate",d,this),delete d.cancelDataUpdate,k===!0)a.raiseEvent("DataUpdateCancelled",d,this);else{j[this.id]=d.data||"";g[this.id]={};if(e!==!0)this.options.safeMode===!0&&this.__state.rendering===!0&&!this.isActive()?(this.__state.updatePending=d,a.raiseWarning(this,"23091255","run","::DataHandler~update","Renderer update was postponed due to async loading.")):
(delete this.__state.updatePending,a.renderer.update(this,d));this.__state.dataReady=void 0;a.raiseEvent("DataUpdated",d,this)}}}},getChartData:function(b,c){var d;var e;if(b===void 0||typeof b.toString!=="function"||(e=i[b=b.toString().toLowerCase()])===void 0)a.raiseError(this,"25081543","param","~getChartData()",Error('Unrecognized data-format specified in "format"'));else return d=typeof g[this.id][b]==="object"?g[this.id][b]:g[this.id][b]=e.decode(j[this.id],this,this.options.dataConfiguration),
e=d,Boolean(c)===!0?e:e.data},dataReady:function(){return this.__state.dataReady}},!0);a.extend(a.core,{transcodeData:function(b,c,e,f,k){if(!c||typeof c.toString!=="function"||!e||typeof e.toString!=="function"||i[e=e.toString().toLowerCase()]===void 0||i[c=c.toString().toLowerCase()]===void 0)a.raiseError(this,"14090217","param","transcodeData()",Error("Unrecognized data-format specified during transcoding."));else{b=i[c].encode(b,this,k);e=i[e].decode(b.data,this,k);if(!(e.error instanceof Error))e.error=
b.error;return f?e:e.data}}},!1);a.addEventListener("Disposed",function(a){delete g[a.sender.id]});a.addEventListener("Loaded",function(b){b=b.sender;b instanceof a.core&&b.__state.updatePending!==void 0&&(a.renderer.update(b,b.__state.updatePending),delete b.__state.updatePending)});a.addEventListener("NoDataToDisplay",function(a){a.sender.__state.dataReady=!1});var e=a._interactiveCharts={selectscatter:[!0,!1],dragcolumn2d:[!0,!0],dragarea:[!0,!0],dragline:[!0,!0],dragnode:[!0,!0]};a.addEventListener("Loaded",
function(b){var b=b.sender,c=b.__state,h,f;if(b.chartType&&e[b.chartType()]&&e[b.chartType()][0]){for(h in a.transcoders)f=a.transcoders[h].name,f="get"+f+"Data",b[f]=function(b,f){return function(c){return c===!1?f.apply(this):this.ref.getUpdatedXMLData?a.core.transcodeData(this.ref.getUpdatedXMLData(),"xml",b):this.getData?this.getData(b):f.apply(this)}}(h,b.constructor.prototype[f]),b[f]._dynamicdatarouter=!0;c.dynamicDataRoutingEnabled=!0}else if(c.dynamicDataRoutingEnabled){for(h in a.transcoders)f=
a.transcoders[h].name,f="get"+f+"Data",b.hasOwnProperty(f)&&b[f]._dynamicdatarouter&&delete b[f];c.dynamicDataRoutingEnabled=!1}})}})();
var swfobject=window.swfobject=function(){function a(){if(!B){try{var a=q.getElementsByTagName("body")[0].appendChild(q.createElement("span"));a.parentNode.removeChild(a)}catch(b){return}B=!0;for(var a=F.length,f=0;f<a;f++)F[f]()}}function i(a){B?a():F[F.length]=a}function j(a){if(typeof v.addEventListener!=u)v.addEventListener("load",a,!1);else if(typeof q.addEventListener!=u)q.addEventListener("load",a,!1);else if(typeof v.attachEvent!=u)s(v,"onload",a);else if(typeof v.onload=="function"){var b=
v.onload;v.onload=function(){b();a()}}else v.onload=a}function g(){var a=q.getElementsByTagName("body")[0],b=q.createElement(x);b.setAttribute("type",E);var f=a.appendChild(b);if(f){var d=0;(function(){if(typeof f.GetVariable!=u){var k;try{k=f.GetVariable("$version")}catch(e){}if(k)k=k.split(" ")[1].split(","),o.pv=[parseInt(k[0],10),parseInt(k[1],10),parseInt(k[2],10)]}else if(d<10){d++;setTimeout(arguments.callee,10);return}a.removeChild(b);f=null;c()})()}else c()}function c(){var a=y.length;if(a>
0)for(var f=0;f<a;f++){var c=y[f].id,d=y[f].callbackFn,m=y[f].userData||{};m.success=!1;m.id=c;if(o.pv[0]>0){var g=k(c);if(g)if(p(y[f].swfVersion)&&!(o.wk&&o.wk<312)){if(n(c,!0),d)m.success=!0,m.ref=h(c),d(m)}else if(y[f].expressInstall&&l()){m={};m.data=y[f].expressInstall;m.width=g.getAttribute("width")||"0";m.height=g.getAttribute("height")||"0";if(g.getAttribute("class"))m.styleclass=g.getAttribute("class");if(g.getAttribute("align"))m.align=g.getAttribute("align");for(var s={},g=g.getElementsByTagName("param"),
i=g.length,j=0;j<i;j++)g[j].getAttribute("name").toLowerCase()!="movie"&&(s[g[j].getAttribute("name")]=g[j].getAttribute("value"));e(m,s,c,d)}else b(g),d&&d(m)}else if(n(c,!0),d){if((c=h(c))&&typeof c.SetVariable!=u)m.success=!0,m.ref=c;d(m)}}}function h(a){var b,f=null;if(!document.embeds||!(b=document.embeds[a]))if(!((b=k(a))&&b.nodeName=="OBJECT"))b=window[a];if(!b)return f;typeof b.SetVariable!=u?f=b:(a=b.getElementsByTagName(x)[0])&&(f=a);return f}function l(){return!G&&p("6.0.65")&&(o.win||
o.mac)&&!(o.wk&&o.wk<312)}function e(a,b,f,c){G=!0;J=c||null;L={success:!1,id:f};var e=k(f);if(e){e.nodeName=="OBJECT"?(D=d(e),H=null):(D=e,H=f);a.id=w;if(typeof a.width==u||!/%$/.test(a.width)&&parseInt(a.width,10)<310)a.width="310";if(typeof a.height==u||!/%$/.test(a.height)&&parseInt(a.height,10)<137)a.height="137";q.title=q.title.slice(0,47)+" - Flash Player Installation";c=o.ie&&o.win?"ActiveX":"PlugIn";c="MMredirectURL="+v.location.toString().replace(/&/g,"%26")+"&MMplayerType="+c+"&MMdoctitle="+
q.title;typeof b.flashvars!=u?b.flashvars+="&"+c:b.flashvars=c;if(o.ie&&o.win&&e.readyState!=4)c=q.createElement("div"),f+="SWFObjectNew",c.setAttribute("id",f),e.parentNode.insertBefore(c,e),e.style.display="none",function(){e.readyState==4?e.parentNode.removeChild(e):setTimeout(arguments.callee,10)}();t(a,b,f)}}function b(a){if(o.ie&&o.win&&a.readyState!=4){var b=q.createElement("div");a.parentNode.insertBefore(b,a);b.parentNode.replaceChild(d(a),b);a.style.display="none";(function(){a.readyState==
4?a.parentNode.removeChild(a):setTimeout(arguments.callee,10)})()}else a.parentNode.replaceChild(d(a),a)}function d(a){var b=q.createElement("div");if(o.win&&o.ie)b.innerHTML=a.innerHTML;else if(a=a.getElementsByTagName(x)[0])if(a=a.childNodes)for(var f=a.length,c=0;c<f;c++)!(a[c].nodeType==1&&a[c].nodeName=="PARAM")&&a[c].nodeType!=8&&b.appendChild(a[c].cloneNode(!0));return b}function t(a,b,f){var c,f=k(f);if(o.wk&&o.wk<312)return c;if(f){if(typeof a.id==u)a.id=f.id;if(o.ie&&o.win){var d="",e;for(e in a)if(a[e]!=
Object.prototype[e])e.toLowerCase()=="data"?b.movie=a[e]:e.toLowerCase()=="styleclass"?d+=' class="'+a[e]+'"':e.toLowerCase()!="classid"&&(d+=" "+e+'="'+a[e]+'"');e="";for(var m in b)b[m]!=Object.prototype[m]&&(e+='<param name="'+m+'" value="'+b[m]+'" />');f.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+d+">"+e+"</object>";I[I.length]=a.id;c=k(a.id)}else{m=q.createElement(x);m.setAttribute("type",E);for(var h in a)a[h]!=Object.prototype[h]&&(h.toLowerCase()=="styleclass"?
m.setAttribute("class",a[h]):h.toLowerCase()!="classid"&&m.setAttribute(h,a[h]));for(d in b)b[d]!=Object.prototype[d]&&d.toLowerCase()!="movie"&&(a=m,e=d,h=b[d],c=q.createElement("param"),c.setAttribute("name",e),c.setAttribute("value",h),a.appendChild(c));f.parentNode.replaceChild(m,f);c=m}}return c}function f(a){var b=k(a);if(b&&b.nodeName=="OBJECT")o.ie&&o.win?(b.style.display="none",function(){if(b.readyState==4){var f=k(a);if(f){for(var c in f)typeof f[c]=="function"&&(f[c]=null);f.parentNode.removeChild(f)}}else setTimeout(arguments.callee,
10)}()):b.parentNode.removeChild(b)}function k(a){var b=null;try{b=q.getElementById(a)}catch(f){}return b}function s(a,b,f){a.attachEvent(b,f);C[C.length]=[a,b,f]}function p(a){var b=o.pv,a=a.split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||0;a[2]=parseInt(a[2],10)||0;return b[0]>a[0]||b[0]==a[0]&&b[1]>a[1]||b[0]==a[0]&&b[1]==a[1]&&b[2]>=a[2]?!0:!1}function m(a,b,f,c){if(!o.ie||!o.mac){var d=q.getElementsByTagName("head")[0];if(d){f=f&&typeof f=="string"?f:"screen";c&&(K=z=null);if(!z||K!=
f)c=q.createElement("style"),c.setAttribute("type","text/css"),c.setAttribute("media",f),z=d.appendChild(c),o.ie&&o.win&&typeof q.styleSheets!=u&&q.styleSheets.length>0&&(z=q.styleSheets[q.styleSheets.length-1]),K=f;o.ie&&o.win?z&&typeof z.addRule==x&&z.addRule(a,b):z&&typeof q.createTextNode!=u&&z.appendChild(q.createTextNode(a+" {"+b+"}"))}}}function n(a,b){if(M){var f=b?"visible":"hidden";B&&k(a)?k(a).style.visibility=f:m("#"+a,"visibility:"+f)}}function r(a){return/[\\\"<>\.;]/.exec(a)!=null&&
typeof encodeURIComponent!=u?encodeURIComponent(a):a}var u="undefined",x="object",E="application/x-shockwave-flash",w="SWFObjectExprInst",v=window,q=document,A=navigator,N=!1,F=[function(){N?g():c()}],y=[],I=[],C=[],D,H,J,L,B=!1,G=!1,z,K,M=!0,o=function(){var a=typeof q.getElementById!=u&&typeof q.getElementsByTagName!=u&&typeof q.createElement!=u,b=A.userAgent.toLowerCase(),f=A.platform.toLowerCase(),c=f?/win/.test(f):/win/.test(b),f=f?/mac/.test(f):/mac/.test(b),b=/webkit/.test(b)?parseFloat(b.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,
"$1")):!1,d=!+"\u000b1",e=[0,0,0],k=null;if(typeof A.plugins!=u&&typeof A.plugins["Shockwave Flash"]==x){if((k=A.plugins["Shockwave Flash"].description)&&!(typeof A.mimeTypes!=u&&A.mimeTypes[E]&&!A.mimeTypes[E].enabledPlugin))N=!0,d=!1,k=k.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),e[0]=parseInt(k.replace(/^(.*)\..*$/,"$1"),10),e[1]=parseInt(k.replace(/^.*\.(.*)\s.*$/,"$1"),10),e[2]=/[a-zA-Z]/.test(k)?parseInt(k.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if(typeof v.ActiveXObject!=u)try{var m=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");
if(m){try{k=m.GetVariable("$version")}catch(h){}k&&(d=!0,k=k.split(" ")[1].split(","),e=[parseInt(k[0],10),parseInt(k[1],10),parseInt(k[2],10)])}}catch(g){}return{w3:a,pv:e,wk:b,ie:d,win:c,mac:f}}();(function(){o.w3&&((typeof q.readyState!=u&&q.readyState=="complete"||typeof q.readyState==u&&(q.getElementsByTagName("body")[0]||q.body))&&a(),B||(typeof q.addEventListener!=u&&q.addEventListener("DOMContentLoaded",a,!1),o.ie&&o.win&&(q.attachEvent("onreadystatechange",function(){q.readyState=="complete"&&
(q.detachEvent("onreadystatechange",arguments.callee),a())}),v==top&&function(){if(!B){try{q.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,0);return}a()}}()),o.wk&&function(){B||(/loaded|complete/.test(q.readyState)?a():setTimeout(arguments.callee,0))}(),j(a)))})();(function(){o.ie&&o.win&&window.attachEvent("onunload",function(){for(var a=C.length,b=0;b<a;b++)C[b][0].detachEvent(C[b][1],C[b][2]);a=I.length;for(b=0;b<a;b++)f(I[b]);for(var c in o)o[c]=null;o=null;for(var d in swfobject)swfobject[d]=
null;swfobject=null})})();return{FusionChartsModified:!0,registerObject:function(a,b,f,c,d){var e=d||{};if(o.w3&&a&&b)e.id=a,e.swfVersion=b,e.expressInstall=f,e.callbackFn=c,e.userData=d,y[y.length]=e,n(a,!1);else if(c)e.success=!1,e.id=a,c(e)},getObjectById:function(a){if(o.w3)return h(a)},embedSWF:function(a,b,f,c,d,k,m,h,g,s,j){var r=j||{};r.success=!1;r.id=b;o.w3&&!(o.wk&&o.wk<312)&&a&&b&&f&&c&&d?(n(b,!1),i(function(){f+="";c+="";var j={};if(g&&typeof g===x)for(var i in g)j[i]=g[i];j.data=a;j.width=
f;j.height=c;i={};if(h&&typeof h===x)for(var o in h)i[o]=h[o];if(m&&typeof m===x)for(var q in m)typeof i.flashvars!=u?i.flashvars+="&"+q+"="+m[q]:i.flashvars=q+"="+m[q];if(p(d))o=t(j,i,b),j.id==b&&n(b,!0),r.success=!0,r.ref=o;else if(k&&l()){j.data=k;e(j,i,b,s);return}else n(b,!0);s&&s(r)})):s&&s(r)},switchOffAutoHideShow:function(){M=!1},ua:o,getFlashPlayerVersion:function(){return{major:o.pv[0],minor:o.pv[1],release:o.pv[2]}},hasFlashPlayerVersion:p,createSWF:function(a,b,f){if(o.w3)return t(a,
b,f)},showExpressInstall:function(a,b,f,c){o.w3&&l()&&e(a,b,f,c)},removeSWF:function(a){o.w3&&f(a)},createCSS:function(a,b,f,c){o.w3&&m(a,b,f,c)},addDomLoadEvent:i,addLoadEvent:j,getQueryParamValue:function(a){var b=q.location.search||q.location.hash;if(b){/\?/.test(b)&&(b=b.split("?")[1]);if(a==null)return r(b);for(var b=b.split("&"),f=0;f<b.length;f++)if(b[f].substring(0,b[f].indexOf("="))==a)return r(b[f].substring(b[f].indexOf("=")+1))}return""},expressInstallCallback:function(){if(G){var a=k(w);
if(a&&D){a.parentNode.replaceChild(D,a);if(H&&(n(H,!0),o.ie&&o.win))D.style.display="block";J&&J(L)}G=!1}}}}();
FusionCharts(["private","modules.renderer.flash",function(){var a=this,i=window,j=document,g=function(a){return typeof a==="function"},c=i.encodeURIComponent?function(a){return i.encodeURIComponent(a)}:function(a){return i.escape(a)};try{a.swfobject=i.swfobject,i.swfobject.createCSS("object.FusionCharts:focus, embed.FusionCharts:focus","outline: none")}catch(h){}a.core.options.requiredFlashPlayerVersion="8";a.core.options.flashInstallerUrl="http://get.adobe.com/flashplayer/";a.core.options.installRedirectMessage=
"You need Adobe Flash Player 8 (or above) to view the charts on this page. It is a free, lightweight and safe installation from Adobe Systems Incorporated.\n\nWould you like to go to Adobe's website and install Flash Player?";a.core.hasRequiredFlashVersion=function(b){if(typeof b==="undefined")b=a.core.options.requiredFlashPlayerVersion;return i.swfobject?i.swfobject.hasFlashPlayerVersion(b):void 0};var l=!1,e=/.*?\%\s*?$/g,b={chartWidth:!0,chartHeight:!0,mapWidth:!0,mapHeight:!0},d=function(b,c){if(!(c&&
c.source==="XmlHttpRequest")){var e=b.sender;if(e.ref&&g(e.ref.dataInvokedOnSWF)&&e.ref.dataInvokedOnSWF()&&g(e.ref.getXML))a.raiseWarning(e,"08300116","run","::DataHandler~__fusioncharts_vars","Data was set in UTF unsafe manner"),e.setChartData(i.unescape(b.sender.ref.getXML({escaped:!0})),FusionChartsDataFormats.XML,!0),e.flashVars.dataXML=e.getChartData(FusionChartsDataFormats.XML),delete e.flashVars.dataURL;b.sender.removeEventListener("DataLoaded",d)}};i.__fusioncharts_dimension=function(){return function(b){var c,
d;return!((c=a.core(b))instanceof a.core&&c.ref&&(d=c.ref.parentNode))?{}:{width:d.offsetWidth*(e.test(c.width)?parseInt(c.width,10)/100:1),height:d.offsetHeight*(e.test(c.height)?parseInt(c.height,10)/100:1)}}}();i.__fusioncharts_vars=function(b,c){var e=a.core.items[b];if(!(e instanceof a.core))return setTimeout(function(){var c;if(c=b!==void 0){var d=i.swfobject.getObjectById(b),e,k,h;c={};var j;if(!d&&typeof d.tagName!=="string")c=void 0;else{if((e=d.parentNode)&&e.tagName&&e.tagName.toLowerCase()===
"object"&&e.parentNode)e=e.parentNode;if(e){c.renderAt=e;if(!(d.tagName.toLowerCase()!=="object"&&d.getAttribute&&(j=d.getAttribute("flashvars")||""))&&d.hasChildNodes&&d.hasChildNodes()){h=d.childNodes;e=0;for(d=h.length;e<d;e+=1)if(h[e].tagName==="PARAM"&&(k=h[e].getAttribute("name"))&&k.toLowerCase()==="flashvars")j=h[e].getAttribute("value")||""}if(j&&g(j.toString)){j=j.split(/\=|&/g);c.flashVars={};e=0;for(d=j.length;e<d;e+=2)c.flashVars[j[e]]=j[e+1]}}else c=void 0}}c||a.raiseError(a.core,"25081621",
"run","::FlashRenderer","FusionCharts Flash object is accessing flashVars of non-existent object.")},0),!1;if(typeof c==="object"){if(e.ref&&g(e.ref.dataInvokedOnSWF)&&e.ref.dataInvokedOnSWF()){if(c.dataURL!==void 0)e.addEventListener("DataLoaded",d);else if(c.dataXML!==void 0)c.dataXML=i.unescape(c.dataXML);e.__state.flashUpdatedFlashVars=!0}else delete c.dataURL,delete c.dataXML;a.extend(e.flashVars,c);return!0}if(e.__state.dataSetDuringConstruction&&e.flashVars.dataXML===void 0&&e.options.dataSource!==
void 0&&typeof e.options.dataFormat==="string")e.flashVars.dataXML=e.options.dataSource;e.__state.flashInvokedFlashVarsRequest=!0;return e.flashVars};i.__fusioncharts_event=function(b,c){setTimeout(function(){a.raiseEvent(b.type,c,a.core.items[b.sender])},0)};var t=function(b){b=b.sender;if(b.options.renderer==="flash"){if(b.width===void 0)b.width=a.renderer.policies.flashVars.chartWidth[1];if(b.height===void 0)b.height=a.renderer.policies.flashVars.chartHeight[1];if(b.flashVars.DOMId===void 0)b.flashVars.DOMId=
b.id;a.extend(b.flashVars,{registerWithJS:"1",chartWidth:b.width,chartHeight:b.height,InvalidXMLText:"Invalid data."});if(Boolean(b.options.autoInstallRedirect)===!0&&!i.swfobject.hasFlashPlayerVersion(a.core.options.requiredFlashPlayerVersion.toString())&&l===!1&&(l=!0,a.core.options.installRedirectMessage&&i.confirm(a.core.options.installRedirectMessage)))i.location.href=a.core.options.flashInstallerUrl;if(b.options.dataFormat===void 0&&b.options.dataSource===void 0)b.options.dataFormat=FusionChartsDataFormats.XMLURL,
b.options.dataSource="Data.xml"}};a.renderer.register("flash",{dataFormat:"xml",init:function(){a.addEventListener("BeforeInitialize",t)},policies:{params:{scaleMode:["scaleMode","noScale"],scale:["scaleMode","noScale"],wMode:["wMode","opaque"],menu:["menu",void 0],bgColor:["bgColor",void 0],allowScriptAccess:["allowScriptAccess","always"],quality:["quality","best"],swLiveConnect:["swLiveConnect",void 0],base:["base",void 0],align:["align",void 0],salign:["sAlign",void 0]},flashVars:{lang:["lang",
"EN"],debugMode:["debugMode",void 0],scaleMode:["scaleMode","noScale"],animation:["animate",void 0]},options:{autoInstallRedirect:["autoInstallRedirect",!1],useLegacyXMLTransport:["_useLegacyXMLTransport",!1]}},render:function(f,d){Boolean(this.flashVars.animation)===!0&&delete this.flashVars.animation;this.src||a.raiseError(this,"03102348","run","::FlashRenderer.render",'Could not find a valid "src" attribute. swfUrl or chart type missing.');var e={},h=this.flashVars.dataXML,m=this.flashVars.dataURL,
g,j;a.extend(e,this.flashVars);if(this.flashVars.stallLoad===!0){if(this.options.dataFormat===FusionChartsDataFormats.XML)h=this.options.dataSource;if(this.options.dataFormat===FusionChartsDataFormats.XMLURL)m=this.options.dataSource}if(a.core.debugMode.enabled()&&a.core.debugMode.syncStateWithCharts&&e.debugMode===void 0&&this.options.safeMode)e.debugMode="1";this.__state.lastRenderedSrc=this.src;e.dataXML=c(h)||"";e.dataURL=a.isXSSSafe(m)?m||"":c(m)||"";for(g in b)e.hasOwnProperty(g)&&(e[g]=c(e[g]));
if(!i.swfobject||!i.swfobject.embedSWF||!i.swfobject.FusionChartsModified)i.swfobject=a.swfobject;l&&!a.core.options.installRedirectMessage&&(j={silent:!0});i.swfobject&&i.swfobject.embedSWF?i.swfobject.embedSWF(this.src,f.id,this.width,this.height,a.core.options.requiredFlashPlayerVersion,void 0,e,this.params,this.attributes,d,j):a.raiseError(this,"1113061611","run","FlashRenderer~render",Error("Could not find swfobject library or embedSWF API"))},update:function(a){var b=this.ref,c=a.data;this.flashVars.dataXML=
c;a.error===void 0?this.isActive()&&g(b.setDataXML)?this.src!==this.__state.lastRenderedSrc?this.render():b.setDataXML(c,!1):(delete this.flashVars.dataURL,delete this.flashVars.animation):this.isActive()&&g(b.showChartMessage)?b.showChartMessage("InvalidXMLText"):(this.flashVars.dataXML="<Invalid"+a.format.toUpperCase()+">",delete this.flashVars.dataURL,delete this.flashVars.animation)},resize:function(){this.flashVars.chartWidth=this.width;this.flashVars.chartHeight=this.height;if(this.ref!==void 0)this.ref.width=
this.width,this.ref.height=this.height,g(this.ref.resize)&&this.ref.resize(this.ref.offsetWidth,this.ref.offsetHeight)},config:function(b){a.extend(this.flashVars,b)},dispose:function(){var a;i.swfobject.removeSWF(this.id);(a=this.ref)&&a.parentNode&&a.parentNode.removeChild(a)},protectedMethods:{flashVars:!0,params:!0,setDataXML:!0,setDataURL:!0,hasRendered:!0,getXML:!0,getDataAsCSV:!0,print:!0,exportChart:!0},events:{Loaded:function(a){a.sender.flashVars.animation="0"},DataLoadRequested:function(b,
c){var e=b.sender,h=c.url,m=!1;if(c.dataFormat===FusionChartsDataFormats.XML&&(i.location.protocol==="file:"&&Boolean(e.options.safeMode)||Boolean(e.options.useLegacyXMLTransport)))e.ref?e.ref.setDataURL?e.ref.setDataURL(h,!1):a.raiseError(this,"0109112330","run",">FlashRenderer^DataLoadRequested",Error("Unable to fetch URL due to security restriction on Flash Player. Update global security settings.")):e.flashVars.dataURL=h,b.stopPropagation(),m=!0,c.cancelDataLoadRequest(),e.addEventListener("DataLoaded",
d);if(e.ref&&e.showChartMessage)delete e.flashVars.stallLoad,e.options.showDataLoadingMessage&&e.ref.showChartMessage("XMLLoadingText");else if(!m)e.flashVars.stallLoad=!0},DataLoadRequestCancelled:function(a){a=a.sender;a.ref&&g(a.showChartMessage)&&a.ref.showChartMessage();delete a.flashVars.stallLoad},DataLoadError:function(a,b){var c=a.sender;c.ref&&g(c.ref.showChartMessage)&&b.source==="XmlHttpRequest"?c.ref.showChartMessage("LoadDataErrorText"):(delete c.flashVars.dataURL,c.flashVars.dataXML=
"<JSON parsing error>",delete c.flashVars.stallLoad)},DataLoadRequestCompleted:function(a,b){b.source==="XmlHttpRequest"&&delete a.sender.flashVars.stallLoad}},prototype:{getSWFHTML:function(){var a=j.createElement("span"),b=j.createElement("span"),c="RnVzaW9uQ2hhcnRz"+(new Date).getTime();a.appendChild(b);b.setAttribute("id",c);a.style.display="none";j.getElementsByTagName("body")[0].appendChild(a);i.swfobject.embedSWF(this.src,c,this.width,this.height,"8.0.0",void 0,this.flashVars,this.params,this.attrs);
b=a.innerHTML.replace(c,this.id);i.swfobject.removeSWF(c);a.parentNode.removeChild(a);return b},setTransparent:function(a){typeof a!=="boolean"&&a!==null&&(a=!0);this.params.wMode=a===null?"window":a===!0?"transparent":"opaque"},registerObject:function(){},addVariable:function(){a.raiseWarning(this,"1012141919","run","FlashRenderer~addVariable()",'Use of deprecated "addVariable()". Replace with "configure()".');a.core.prototype.configure.apply(this,arguments)},setDataXML:function(b){a.raiseWarning(this,
"11033001081","run","GenericRuntime~setDataXML()",'Use of deprecated "setDataXML()". Replace with "setXMLData()".');b===void 0||b===null||!g(b.toString)?a.raiseError(this,"25081627","param","~setDataXML",'Invalid data type for parameter "xml"'):this.ref===void 0||this.ref===null||!g(this.ref.setDataXML)?this.setChartData(b.toString(),FusionChartsDataFormats.XML):this.ref.setDataXML(b.toString())},setDataURL:function(b){a.raiseWarning(this,"11033001082","run","GenericRuntime~setDataURL()",'Use of deprecated "setDataURL()". Replace with "setXMLUrl()".');
b===void 0||b===null||!g(b.toString)?a.raiseError(this,"25081724","param","~setDataURL",'Invalid data type for parameter "url"'):this.ref===void 0||this.ref===null||!g(this.ref.setDataURL)?this.setChartData(b.toString(),FusionChartsDataFormats.XMLURL):this.ref.setDataURL(b.toString())}}});a.renderer.setDefault("flash")}]);
(function(){var a;a=FusionCharts(["private","modules.renderer.highcharts"]);if(a!==void 0){a.extend(a.core.options,{html5ScriptNameSuffix:".js",html5ScriptNamePrefix:"FusionCharts.HC.",jQuerySourceFileName:"jquery.min.js"});var i=window,j=a.core.options,g=function(){},c=a.hcLib={cmdQueue:[]},h=c.moduleCmdQueue={jquery:[],base:[],charts:[],powercharts:[],widgets:[],maps:[]},l=c.moduleDependencies={},e=c.moduleMeta={jquery:"jquery.min.js",base:"FusionCharts.HC.js",charts:"FusionCharts.HC.Charts.js",
powercharts:"FusionCharts.HC.PowerCharts.js",widgets:"FusionCharts.HC.Widgets.js",maps:"FusionCharts.HC.Maps.js"},b={},d=c.getDependentModuleName=function(a){var b=[],c,f;for(c in l)if((f=l[c][a])!==void 0)b[f]=c;return b};c.injectModuleDependency=function(a,b,f){var e=!1;b===void 0&&(b=a);l[a]||(l[a]={},h[a]||(h[a]=[],c.moduleMeta[a]=j.html5ScriptNamePrefix+b+j.html5ScriptNameSuffix),e=!0);l[a][b]=f||0;return e};var t=c.hasModule=function(b){var c,f;if(b instanceof Array){c=0;for(f=b.length;c<f;c+=
1)if(!Boolean(a.modules["modules.renderer.highcharts-"+b])||b==="jquery"&&!Boolean(window.jQuery))return!1;return!0}if(b==="jquery")return Boolean(window.jQuery);return Boolean(a.modules["modules.renderer.highcharts-"+b])};c.needsModule=function(a,b){return(c.moduleDependencies[a]&&c.moduleDependencies[a][b])!==void 0};var f=c.loadModule=function(c,f,d,h){c instanceof Array||(c=[c]);var k=c.length,g=0,j=function(){if(g>=k)f&&f();else{var i=c[g],l=e[i],p;g+=1;if(i)if(t(i)){j();return}else{if(b[i]){a.raiseError(h||
a.core,"1112201445A","run","JavaScriptRenderer~loadModule() ","required resources are absent or blocked from loading.");d&&d(i);return}}else d&&d(i);p=i==="jquery"?a.core.options.jQuerySourceFileName:a.core.options["html5"+a.capitalizeString(i)+"Src"];a.loadScript(p==void 0?l:p,{success:function(){t(i)?j():d&&d(i)},failure:d&&function(){d(i)}},void 0,!0)}};j()},k=c.executeWaitingCommands=function(a){for(var b;b=a.shift();)typeof b==="object"&&g[b.cmd].apply(b.obj,b.args)};c.cleanupWaitingCommands=
function(a){for(var b=a.chartType(),b=d(b),c,f=[],e;c=b.shift();){for(c=h[c]||[];e=c.shift();)typeof e==="object"&&e.obj!==a&&f.push(e);c.concat(f);f=[]}};var s=function(a){delete a.sender.jsVars._reflowData;a.sender.jsVars._reflowData={};delete a.sender.jsVars._reflowClean},p=function(){var a=function(){};a.prototype={LoadDataErrorText:"Error in loading data.",XMLLoadingText:"Retrieving data. Please wait",InvalidXMLText:"Invalid data.",ChartNoDataText:"No data to display.",ReadingDataText:"Reading data. Please wait",
ChartNotSupported:"Chart type not supported.",LoadingText:"Loading chart. Please wait",RenderChartErrorText:"Unable to render chart."};return a.prototype.constructor=a}();g.dataFormat="json";g.policies={jsVars:{},options:{showLoadingMessage:["showLoadingMessage",!0]}};g.ready=!1;g.init=function(){window.jQuery?t("base")?g.ready=!0:f("base",function(){g.ready=!0;k(c.cmdQueue)},void 0,a.core):f("jquery",function(){jQuery.noConflict();if(window.$===void 0)window.$=jQuery;g.init()},void 0,a.core)};g.render=
function(a){var b=a,f=this.jsVars,e=f.msgStore;if(b&&this.options.showLoadingMessage)b.innerHTML='<small style="display: inline-block; *zoom:1; *display:inline; width: 100%; font-family: Verdana; font-size: 10px; color: #666666; text-align: center; padding-top: '+(parseInt(b.style.height,10)/2-5)+'px">'+e.LoadingText+"</small>",b.style.backgroundColor=f.transparent?this.options.containerBackgroundColor||"transparent":"#ffffff";c.cmdQueue.push({cmd:"render",obj:this,args:arguments})};g.update=function(){c.cmdQueue.push({cmd:"update",
obj:this,args:arguments})};g.resize=function(){c.cmdQueue.push({cmd:"resize",obj:this,args:arguments})};g.dispose=function(){var a=c.cmdQueue,b,f;b=0;for(f=a.length;b<f;b+=1)a[b].obj===this&&(a.splice(b,1),f-=1,b-=1)};g.config=function(){c.cmdQueue.push({cmd:"config",obj:this,args:arguments})};g.load=function(){c.cmdQueue.push({cmd:"load",obj:this,args:arguments})};g.protectedMethods={};g.events={BeforeInitialize:function(a){var b=a.sender,a=b.jsVars,f=this.chartType();a.fcObj=b;a.msgStore=a.msgStore||
new p;a.cfgStore=a.cfgStore||{};a.previousDrawCount=-1;a.drawCount=0;a._reflowData={};if(!(a.userModules instanceof Array)&&(b=a.userModules,a.userModules=[],typeof b==="string"))a.userModules=a.userModules.concat(b.split(","));if(!c.chartAPI||!c.chartAPI[f])a.needsLoaderCall=!0},Initialized:function(a){var a=a.sender,b=a.jsVars;b.needsLoaderCall&&(delete b.needsLoaderCall,g.load.call(a))},BeforeDataUpdate:s,BeforeDispose:s,BeforeRender:function(a){var b=a.sender.jsVars;delete b.drLoadAttempted;delete b.waitingModule;
delete b.waitingModuleError;s.apply(this,arguments)},DataLoadRequested:function(a){var a=a.sender,b=a.jsVars;delete b.loadError;a.ref&&a.options.showDataLoadingMessage?b.hcObj&&!b.hasNativeMessage&&b.hcObj.showLoading?b.hcObj.showLoading(b.msgStore.XMLLoadingText):a.ref.showChartMessage?a.ref.showChartMessage("XMLLoadingText"):b.stallLoad=!0:b.stallLoad=!0},DataLoadRequestCompleted:function(a){delete a.sender.id.stallLoad},DataLoadError:function(a){var b=a.sender,c=b.jsVars;delete c.stallLoad;c.loadError=
!0;b.ref&&typeof b.ref.showChartMessage==="function"&&b.ref.showChartMessage("LoadDataErrorText");s.apply(this,arguments)}};g._call=function(a,b,c){a.apply(c||i,b||[])};a.extend(g.prototype,{getSWFHTML:function(){a.raiseWarning(this,"11090611381","run","JavaScriptRenderer~getSWFHTML()","getSWFHTML() is not supported for JavaScript charts.")},addVariable:function(){a.raiseWarning(this,"11090611381","run","JavaScriptRenderer~addVariable()",'Use of deprecated "addVariable()". Replace with "configure()".');
a.core.prototype.configure.apply(this,arguments)},getXML:function(){a.raiseWarning(this,"11171116291","run","JavaScriptRenderer~getXML()",'Use of deprecated "getXML()". Replace with "getXMLData()".');return this.getXMLData.apply(this,arguments)},setDataXML:function(){a.raiseWarning(this,"11171116292","run","JavaScriptRenderer~setDataXML()",'Use of deprecated "setDataXML()". Replace with "setXMLData()".');return this.setXMLData.apply(this,arguments)},setDataURL:function(){a.raiseWarning(this,"11171116293",
"run","JavaScriptRenderer~setDataURL()",'Use of deprecated "SetDataURL()". Replace with "setXMLUrl()".');return this.setXMLUrl.apply(this,arguments)},hasRendered:function(){return this.jsVars.hcObj&&this.jsVars.hcObj.hasRendered},setTransparent:function(a){var b;if(b=this.jsVars)typeof a!=="boolean"&&a!==null&&(a=!0),b.transparent=a===null?!1:a===!0?!0:!1}});a.extend(a.core,{_fallbackJSChartWhenNoFlash:function(){window.swfobject.hasFlashPlayerVersion(a.core.options.requiredFlashPlayerVersion)||a.renderer.setDefault("javascript")},
_enableJSChartsForSelectedBrowsers:function(b){b===void 0||b===null||a.renderer.setDefault(RegExp(b).test(navigator.userAgent)?"javascript":"flash")},_doNotLoadExternalScript:function(a){var c,f;for(c in a)f=c.toLowerCase(),e[f]&&(b[f]=Boolean(a[c]))},_preloadJSChartModule:function(){throw"NotImplemented()";}});a.renderer.register("javascript",g);window.swfobject&&window.swfobject.hasFlashPlayerVersion&&!window.swfobject.hasFlashPlayerVersion(a.core.options.requiredFlashPlayerVersion)&&(a.raiseWarning(a.core,
"1204111846","run","JSRenderer","Switched to JavaScript as default rendering due to absence of required Flash Player."),a.renderer.setDefault("javascript"))}})();(function(){var a=FusionCharts(["private","XMLDataHandler"]);if(a!==void 0){var i=function(a){return{data:a,error:void 0}};a.addDataHandler("XML",{encode:i,decode:i})}})();var JSON;JSON||(JSON={});
(function(){function a(a){return a<10?"0"+a:a}function i(a){c.lastIndex=0;return c.test(a)?'"'+a.replace(c,function(a){var b=e[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function j(a,c){var f,e,g,p,m=h,n,r=c[a];r&&typeof r==="object"&&typeof r.toJSON==="function"&&(r=r.toJSON(a));typeof b==="function"&&(r=b.call(c,a,r));switch(typeof r){case "string":return i(r);case "number":return isFinite(r)?String(r):"null";case "boolean":case "null":return String(r);
case "object":if(!r)return"null";h+=l;n=[];if(Object.prototype.toString.apply(r)==="[object Array]"){p=r.length;for(f=0;f<p;f+=1)n[f]=j(f,r)||"null";g=n.length===0?"[]":h?"[\n"+h+n.join(",\n"+h)+"\n"+m+"]":"["+n.join(",")+"]";h=m;return g}if(b&&typeof b==="object"){p=b.length;for(f=0;f<p;f+=1)typeof b[f]==="string"&&(e=b[f],(g=j(e,r))&&n.push(i(e)+(h?": ":":")+g))}else for(e in r)Object.prototype.hasOwnProperty.call(r,e)&&(g=j(e,r))&&n.push(i(e)+(h?": ":":")+g);g=n.length===0?"{}":h?"{\n"+h+n.join(",\n"+
h)+"\n"+m+"}":"{"+n.join(",")+"}";h=m;return g}}if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var g=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
c=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h,l,e={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},b;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,c,f){var e;l=h="";if(typeof f==="number")for(e=0;e<f;e+=1)l+=" ";else typeof f==="string"&&(l=f);if((b=c)&&typeof c!=="function"&&(typeof c!=="object"||typeof c.length!=="number"))throw Error("JSON.stringify");return j("",
{"":a})};if(typeof JSON.parse!=="function")JSON.parse=function(a,b){function c(a,e){var d,h,k=a[e];if(k&&typeof k==="object")for(d in k)Object.prototype.hasOwnProperty.call(k,d)&&(h=c(k,d),h!==void 0?k[d]=h:delete k[d]);return b.call(a,e,k)}var e,a=String(a);g.lastIndex=0;g.test(a)&&(a=a.replace(g,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),typeof b==="function"?c({"":e},""):e;throw new SyntaxError("JSON.parse");}})();
(function(){var a=FusionCharts(["private","JSON_DataHandler"]);if(a!==void 0){window.JSON===void 0&&a.raiseError(this,"1113062012","run","JSONDataHandler",Error("Could not find library support for JSON parsing."));a.core.options.allowIESafeXMLParsing=["_allowIESafeXMLParsing",!0];var i=function(a){if(a===null||a===void 0||typeof a.toString!=="function")return"";return a=a.toString().replace(/&/g,"&amp;").replace(/\'/g,"&#39;").replace(/\"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},j=function(){var c=
{arr:{set:!0,trendlines:!0,vtrendlines:!0,line:{trendlines:!0,vtrendlines:!0},data:!0,dataset:!0,lineset:!0,categories:!0,category:!0,linkeddata:!0,application:!0,definition:!0,axis:!0,connectors:!0,connector:{connectors:!0},trendset:!0,row:{rows:!0},column:{columns:!0},label:{labels:!0},color:{colorrange:!0},dial:{dials:!0},pointer:{pointers:!0},point:{trendpoints:!0},process:{processes:!0},task:{tasks:!0},milestone:{milestones:!0},datacolumn:{datatable:!0},text:{datacolumn:!0},alert:{alerts:!0},
groups:{annotations:!0},items:{groups:!0},shapes:!0,shape:{shapes:!0},entitydef:!0,entity:{entitydef:!0}},tag:{chart:"linkedchart",map:"linkedmap",set:"data",vline:{chart:"data",dataset:"data",categories:"category",linkedchart:"data"},apply:{application:"application"},style:{definition:"definition"},marker:{application:"application",definition:"definition"},entity:{entitydef:"entitydef",data:"data"},shape:{shapes:"shapes"},connector:{connectors:{chart:"connector",linkedchart:"connector",map:"connectors",
linkedmap:"connectors"}},annotationgroup:{annotations:"groups"},annotation:{groups:"items"}},attr:{vline:{vline:"true"}},ins:{chart:!0,map:!0},dsv:{dataset:"data",categories:"category"},text:{target:"target",value:"value"},group:{styles:{definition:!0,application:!0},chart:{value:!0,target:!0},linkedchart:{value:!0,target:!0},markers:{definition:!0,application:!0,shapes:!0,connectors:!0},map:{entitydef:!0,data:!0},linkedmap:{entitydef:!0,data:!0}}},h={append:function(a,b,d,h){c.arr[d]&&(c.arr[d]===
!0||c.arr[d][h]===!0)?(b[d]instanceof Array||(b[d]=[]),b[d].push(a)):b[d]=a},child:function(e,b,d,g){var f,k,j,i,l,n;for(f=0;f<b.length;f+=1)switch(j=b[f],k=j.nodeName.toLowerCase(),j.nodeType){case 1:i=h.attr(j.attributes);n=c.ins[k];n===!0&&(l=i,i={},i[k]=l);n=c.attr[k];typeof n==="object"&&a.extend(i,n);if(n=c.tag[k])if(typeof n==="object"&&typeof n[d]==="object")for(l in l=void 0,n[d]){if(g[l]){k=n[d][l];break}}else typeof n==="object"&&typeof n[d]==="string"?k=n[d]:typeof n==="string"&&(k=n);
j.childNodes.length&&((n=c.group[d])&&n[k]?h.child(e,j.childNodes,k,g):h.child(i,j.childNodes,k,g));n=c.group[d];(!n||!n[k])&&h.append(i,e,k,d);break;case 3:if(n=c.text[d])k=n,i=j.data,h.append(i,e,k,d);n=c.dsv[d];if(typeof n==="string"&&g.chart&&parseInt(g.chart.compactdatamode,10))k=n,i=j.data,e[k]=e[k]?e[k]+i:i}},attr:function(a){var b,c={};if(!a||!a.length)return c;for(b=0;b<a.length;b+=1)c[a[b].nodeName.toLowerCase()]=a[b].value||a[b].nodeValue;return c}},g=function(c){var b={},d,j,f;if(typeof c!==
"object"&&typeof c.toString!=="function")return g.errorObject=new TypeError("xml2json.parse()"),b;for(var c=c.toString().replace(/<\!--[\s\S]*?--\>/g,"").replace(/<\?xml[\s\S]*?\?>/ig,"").replace(/&(?!([^;\n\r]+?;))/g,"&amp;$1"),c=c.replace(/^\s\s*/,""),k=/\s/,i=c.length;k.test(c.charAt(i-=1)););c=c.slice(0,i+1);if(!c)return b;try{if(window.DOMParser)d=(new window.DOMParser).parseFromString(c,"text/xml");else if(document.body&&a.core.options.allowIESafeXMLParsing){var p=document.createElement("xml");
p.innerHTML=c;document.body.appendChild(p);d=p.XMLDocument;document.body.removeChild(p)}else d=new ActiveXObject("Microsoft.XMLDOM"),d.async="false",d.loadXML(c);if(!d||!d.childNodes||!(d.childNodes.length===1&&(j=d.childNodes[0])&&j.nodeName&&(f=j.nodeName.toLowerCase())&&(f==="chart"||f==="map")))return g.errorObject=new TypeError("xml2json.parse()"),b}catch(m){g.errorObject=m}j?(j.attributes&&(b[f]=h.attr(j.attributes)),j.childNodes&&h.child(b,j.childNodes,f,b),delete g.errorObject):g.errorObject=
new TypeError("xml2json.parse()");return b};return function(a){delete g.errorObject;return{data:g(a),error:g.errorObject}}}(),g=function(){var a={items:{explode:{data:"set",groups:{annotations:"annotationgroup"},items:{groups:"annotation"}},text:{chart:{target:"target",value:"value"}},dsv:{dataset:{data:"dataset"},categories:{category:"categories"}},attr:{chart:{chart:"chart"},map:{map:"map"},linkedmap:{map:"map"},linkedchart:{chart:"chart"}},group:{styles:{definition:"style",application:"apply"},
map:{data:"entity",entitydef:"entity"},markers:{definition:"marker",application:"marker",shapes:"shape",connectors:"connector"}}},qualify:function(a,c,b){return typeof this.items[a][b]==="object"?this.items[a][b][c]:this.items[a][b]}},h=function(g,e,b,d){var j="",f="",k="",s="",p,m,n;e&&typeof e.toLowerCase==="function"&&(e=e.toLowerCase());if(b===void 0&&g[e])for(p in g[e])if(m=p.toLowerCase(),m==="compactdatamode")d.applyDSV=g[e][p]==1;if(g instanceof Array)for(p=0;p<g.length;p+=1)s+=typeof g[p]===
"string"?i(g[p]):h(g[p],e,b,d);else{for(p in g)m=p.toLowerCase(),g[p]instanceof Array&&(n=a.qualify("group",m,e))?f+="<"+m+">"+h(g[p],n,e,d)+"</"+m+">":typeof g[p]==="object"?(n=a.qualify("attr",m,e))?(k=h(g[p],n,e,d).replace(/\/\>/ig,""),e=m):f+=h(g[p],m,e,d):d.applyDSV&&(n=a.qualify("dsv",m,e))?f+=g[p]:(n=a.qualify("text",m,e))?f+="<"+n+">"+g[p]+"</"+n+">":m==="vline"&&Boolean(g[p])?e="vline":j+=" "+m+'="'+i(g[p]).toString().replace(/\"/ig,"&quot;")+'"';if(n=a.qualify("explode",b,e))e=n;s=(k!==
""?k:"<"+e)+j+(f!==""?">"+f+"</"+e+">":" />")}return s};return function(a){delete h.errorObject;if(a&&typeof a==="string")try{a=JSON.parse(a)}catch(c){h.errorObject=c}return{data:h(a,a&&a.map?"map":"chart",void 0,{}),error:h.errorObject}}}();a.addDataHandler("JSON",{encode:g,decode:j})}})();
(function(){var a=FusionCharts(["private","CSVDataHandler"]);if(a!==void 0){var i=function(a){this._data=[];this.columnCount=this.rowCount=0;this.configure(a)};i.prototype.set=function(a,g,c){var h;if(this.rowCount<=a){for(h=this.rowCount;h<=a;h+=1)this._data[h]=[];this.rowCount=a+1}if(this.columnCount<=g)this.columnCount=g+1;this._data[a][g]=c};i.prototype.configure=function(a){this.delimiter=this._decodePseudoCode(a.delimiter,",");this.qualifier=this._decodePseudoCode(a.qualifier,'"');this.eolCharacter=
this._decodePseudoCode(a.eolCharacter,"\r\n")};i.prototype._decodePseudoCode=function(a,g){if(a===void 0||a===null||!a.toString)return g;return a.replace("{tab}","\t").replace("{quot}",'"').replace("{apos}","'")};i.prototype.toString=function(){var a,g,c="";for(a=0;a<this.rowCount;a+=1)g=this.qualifier+this._data[a].join(this.qualifier+this.delimiter+this.qualifier)+this.qualifier,c+=g==='""'?this.eolCharacter:g+this.eolCharacter;this.rowCount>0&&(c=c.slice(0,c.length-2));return c};a.addDataHandler("CSV",
{encode:function(i,g){a.raiseError(g,"0604111215A","run","::CSVDataHandler.encode()","FusionCharts CSV data-handler only supports encoding of data.");throw"FeatureNotSupportedException()";},decode:function(j){var j=a.core.transcodeData(j,"xml","json")||{},g,c,h,l,e,b;if(typeof j.chart!=="object")j.chart={};g=new i({separator:j.chart.exportdataseparator,qualifier:j.chart.exportdataqualifier});if(j.dataset&&j.categories&&j.categories[0]&&j.categories[0].category)for(c=0;c<j.dataset.length;c+=1){g.set(0,
c+1,j.dataset[c].seriesname);l=h=0;for(e=j.categories[0].category.length;h<e;h+=1)j.categories[0].category[h].vline||(g.set(l+1,0,j.categories[0].category[h].label||j.categories[0].category[h].name),b=parseFloat(j.dataset[c]&&j.dataset[c].data&&j.dataset[c].data[l]?j.dataset[c].data[l].value:""),b=isNaN(b)?"":b,g.set(l+1,c+1,b),l+=1)}else if(j.data instanceof Array){g.set(0,1,j.chart&&j.chart.yaxisname?j.chart.yaxisname:"Value");e=j.data.length;for(c=0;c<e;c+=1)j.data[c].vline||(g.set(c+1,0,j.data[c].label||
j.data[c].name),b=parseFloat(j.data[c].value?j.data[c].value:""),b=isNaN(b)?"":b,g.set(c+1,1,b))}g.rowCount>0&&g.set(0,0,j.chart&&j.chart.xaxisname?j.chart.xaxisname:"Label");return{data:g.toString(),error:void 0}}});a.core.addEventListener("Loaded",function(a){a=a.sender;if(a.options.renderer==="javascript"&&!a.getDataAsCSV)a.getDataAsCSV=a.ref.getDataAsCSV=a.getCSVData})}})();
(function(){var a=FusionCharts(["private","DynamicChartAttributes"]);a!==void 0&&a.extend(a.core,{setChartAttribute:function(a,j){if(typeof a==="string"){var g=a,a={};a[g]=j}else if(a===null||typeof a!=="object")return;var g=0,c=this.getChartData(FusionChartsDataFormats.JSON),h,l=c.chart||c.graph||c.map||{};for(h in a)g+=1,a[h]===null?delete l[h.toLowerCase()]:l[h.toLowerCase()]=a[h];if(g>0){if(typeof l.animation==="undefined")l.animation="0";this.setChartData(c,FusionChartsDataFormats.JSON)}},getChartAttribute:function(i){var j=
(j=this.getChartData(FusionChartsDataFormats.JSON)).chart||j.graph||j.map;if(arguments.length===0||i===void 0||j===void 0)return j;var g,c;if(typeof i==="string")g=j[i.toString().toLowerCase()];else if(i instanceof Array){g={};for(c=0;c<i.length;c+=1)g[i[c]]=j[i[c].toString().toLowerCase()]}else a.raiseError(this,"25081429","param","~getChartAttribute()",'Unexpected value of "attribute"');return g}},!0)})();
(function(){var a=FusionCharts(["private","api.LinkManager"]);if(a!==void 0){a.policies.link=["link",void 0];var i=window.FusionChartsDOMInsertModes={REPLACE:"replace",APPEND:"append",PREPEND:"prepend"},j={},g=function(c,g){this.items={};this.root=c;this.parent=g;g instanceof a.core?this.level=this.parent.link.level+1:(j[c.id]=[{}],this.level=0)},c=function(a,c){return(a.options.containerElement===c.options.containerElement||a.options.containerElementId===c.options.containerElementId)&&a.options.insertMode===
i.REPLACE};g.prototype.configuration=function(){return j[this.root.id][this.level]||(j[this.root.id][this.level]={})};a.extend(a.core,{configureLink:function(c,g){var e;if(c instanceof Array){for(e=0;e<c.length;e+=1)typeof j[this.link.root.id][e]!=="object"&&(j[this.link.root.id][e]={}),a.extend(j[this.link.root.id][e],c[e]);j[this.link.root.id].splice(c.length)}else if(typeof c==="object"){if(typeof g!=="number")g=this.link.level;j[this.link.root.id][g]===void 0&&(j[this.link.root.id][g]={});a.extend(j[this.link.root.id][g],
c)}else a.raiseError(this,"25081731","param","~configureLink()","Unable to update link configuration from set parameters")}},!0);a.addEventListener("BeforeInitialize",function(c){if(c.sender.link instanceof g){if(c.sender.link.parent instanceof a.core)c.sender.link.parent.link.items[c.sender.id]=c.sender}else c.sender.link=new g(c.sender)});a.addEventListener("LinkedChartInvoked",function(h,i){var e=h.sender,b=e.clone({dataSource:i.data,dataFormat:i.linkType,link:new g(e.link.root,e)},!0),d=i.alias;
if(d){if(!b.swfSrcPath&&b.swfUrl)b.swfSrcPath=b.swfUrl.replace(/(.*?)?[^\/]*\.swf.*?/ig,"$1");b.type=d}e.args&&parseInt(e.args.animate,10)!==0&&delete b.animate;a.extend(b,e.link.configuration());a.raiseEvent("BeforeLinkedItemOpen",{level:e.link.level},e.link.root);a.core.items[b.id]instanceof a.core&&a.core.items[b.id].dispose();b=new a.core(b);if(!c(b,e)&&(!e.options.overlayButton||!e.options.overlayButton.message)){if(typeof e.options.overlayButton!=="object")e.options.overlayButton={};e.options.overlayButton.message=
"Close"}b.render();a.raiseEvent("LinkedItemOpened",{level:e.link.level,item:b},e.link.root)});a.addEventListener("OverlayButtonClick",function(g,i){if(i.id==="LinkManager"){var e=g.sender,b=e.link.level-1,d=e.link.parent,j=e.link.root;a.raiseEvent("BeforeLinkedItemClose",{level:b,item:e},j);setTimeout(function(){a.core.items[e.id]&&e.dispose();a.raiseEvent("LinkedItemClosed",{level:b},j)},0);!d.isActive()&&c(e,d)&&d.render()}});a.addEventListener("Loaded",function(c){if((c=c.sender)&&c.link!==void 0&&
c.link.root!==c&&c.link.parent instanceof a.core)if(c.ref&&typeof c.ref.drawOverlayButton==="function"){var g=a.extend({show:!0,id:"LinkManager"},c.link.parent.options.overlayButton);a.extend(g,c.link.parent.link.configuration().overlayButton||{});c.ref.drawOverlayButton(g)}else a.raiseWarning(c,"04091602","run","::LinkManager^Loaded","Unable to draw overlay button on object. -"+c.id)});a.addEventListener("BeforeDispose",function(c){var i=c.sender;i&&i.link instanceof g&&(i.link.parent instanceof
a.core&&delete i.link.parent.link.items[c.sender.id],delete j[i.id])});FusionChartsEvents.LinkedItemOpened="linkeditemopened";FusionChartsEvents.BeforeLinkedItemOpen="beforelinkeditemopen";FusionChartsEvents.LinkedItemClosed="linkeditemclosed";FusionChartsEvents.BeforeLinkedItemClose="beforelinkeditemclose"}})();
(function(){var a=FusionCharts(["private","PrintManager"]);if(a!==void 0){var i={enabled:!1,invokeCSS:!0,processPollInterval:2E3,message:"Chart is being prepared for print.",useExCanvas:!1,bypass:!1},j={getCanvasElementOf:function(b,c,e){if(b.__fusioncharts__canvascreated!==!0){var d=document.createElement("canvas"),g=a.core.items[b.id].attributes["class"];i.useExCanvas&&G_vmlCanvasManager&&G_vmlCanvasManager.initElement(d);d.setAttribute("class",g);d.__fusioncharts__reference=b.id;b.parentNode.insertBefore(d,
b.nextSibling);b.__fusioncharts__canvascreated=!0}b.nextSibling.setAttribute("width",c||b.offsetWidth||2);b.nextSibling.setAttribute("height",e||b.offsetHeight||2);return b.nextSibling},removeCanvasElementOf:function(a){var b=a.ref&&a.ref.parentNode?a.ref.parentNode:a.options.containerElement||window.getElementById(a.options.containerElementId);if(b){var c=b.getElementsByTagName("canvas"),e,d;d=0;for(e=c.length;d<e;d+=1)if(c[d].__fusioncharts__reference===a.id&&(b.removeChild(c[d]),a.ref))a.ref.__fusioncharts__canvascreated=
!1}},rle2rgba:function(a,b,c){typeof c!=="string"&&(c="FFFFFF");var a=a.split(/[;,_]/),e,d,g,h,i,j=0;for(d=0;d<a.length;d+=2){a[d]===""&&(a[d]=c);a[d]=("000000"+a[d]).substr(-6);g=parseInt("0x"+a[d].substring(0,2),16);h=parseInt("0x"+a[d].substring(2,4),16);i=parseInt("0x"+a[d].substring(4,6),16);for(e=0;e<a[d+1];e+=1)b[j]=g,b[j+1]=h,b[j+2]=i,b[j+3]=255,j+=4}return b},rle2array:function(a,b){typeof b!=="string"&&(b="FFFFFF");var c=a.split(";"),e,d;for(e in c){c[e]=c[e].split(/[_,]/);for(d=0;d<c[e].length;d+=
2)c[e][d]=c[e][d]===""?b:("000000"+c[e][d]).substr(-6)}return c},drawText:function(b,c,e,d){b=b.getContext("2d");e=e||2;d=d||2;b.clearRect(0,0,e,d);b.textBaseline="middle";b.textAlign="center";b.font="8pt verdana";b.fillStyle="#776666";typeof b.fillText==="function"?b.fillText(c,e/2,d/2):typeof b.mozDrawText==="function"?(b.translate(e/2,d/2),b.mozDrawText(c)):a.raiseWarning(a.core,"25081803","run","::PrintManager>lib.drawText","Canvas text drawing is not supported in browser");return!0},appendCSS:function(a){var b=
document.createElement("style");b.setAttribute("type","text/css");typeof b.styleSheet==="undefined"?b.appendChild(document.createTextNode(a)):b.styleSheet.cssText=a;return document.getElementsByTagName("head")[0].appendChild(b)}};j.drawRLE=function(a,b,c,e,d){c=c||2;e=e||2;a.setAttribute("width",c);a.setAttribute("height",e);a=a.getContext("2d");if(typeof a.putImageData==="function"&&typeof a.createImageData==="function")c=a.createImageData(c,e),j.rle2rgba(b,c.data,d),a.putImageData(c,0,0);else for(d in c=
j.rle2array(b,d),e=d=b=0,c)for(e=b=0;e<c[d].length;e+=2)a.fillStyle="#"+c[d][e],a.fillRect(b,d,c[d][e+1],1),b+=parseInt(c[d][e+1],10);return!0};var g={styles:{print:"canvas.FusionCharts{display:none;}@media print{object.FusionCharts{display:none;}canvas.FusionCharts{display:block;}}",error:"canvas.FusionCharts{display:none;}",normal:""},cssNode:void 0},c={},h={},l=0,e;g.invoke=function(a){typeof this.styles[a]!=="undefined"&&(a=this.styles[a]);if(typeof a!=="undefined")this.cssNode!==void 0&&this.cssNode.parentNode!==
void 0&&this.cssNode.parentNode.removeChild(this.cssNode),g.cssNode=j.appendCSS(a)};var b=function(b){var d=b.sender.ref,h,p;if(d===void 0||typeof d.prepareImageDataStream!=="function"||d.prepareImageDataStream()===!1)e(b.sender);else{c[b.sender.id]||(c[b.sender.id]=d,l+=1,l===1&&a.raiseEvent("PrintReadyStateChange",{ready:!1,bypass:i.bypass},b.sender));try{h=d.offsetWidth,p=d.offsetHeight,j.drawText(j.getCanvasElementOf(d,h,p),i.message,h,p)}catch(m){g.invoke("error"),a.raiseError(b.sender,"25081807",
"run","::PrintManager>onDrawComplete","There was an error while showing message to user via canvas.")}}},d=function(b,d){try{j.drawRLE(j.getCanvasElementOf(b.sender.ref,d.width,d.height),d.stream,d.width,d.height,d.bgColor)===!0&&c[b.sender.id]&&(delete c[b.sender.id],l-=1,l===0&&a.raiseEvent("PrintReadyStateChange",{ready:!0,bypass:i.bypass},b.sender))}catch(e){g.invoke("error"),a.raiseError(b.sender,"25081810","run","::PrintManager>onImageStreamReady","There was an error while drawing canvas.")}},
t=function(a){j.removeCanvasElementOf(a.sender)};e=function(c){var d;if(c instanceof a.core)h[c.id]=c;else for(d in h)b({sender:h[d]},{}),delete h[d]};a.extend(a.core,{printManager:{configure:function(b){a.extend(i,b||{})},isReady:function(){if(i.bypass)return!0;if(l>0||!i.enabled)return!1;var b,c;for(b in a.core.items)if((c=a.core.items[b].ref)!==void 0&&c.hasRendered&&c.hasRendered()===!1)return!1;return!0},enabled:function(c){if(c===void 0)return i.enabled;if(a.renderer.currentRendererName()!==
"flash"||typeof document.createElement("canvas").getContext!=="function")return i.bypass=!0,a.raiseEvent("PrintReadyStateChange",{ready:!0,bypass:i.bypass}),a.raiseWarning(a.core,"25081816","run",".printManager.enabled","printManager is not compatible with your browser"),i.enabled;i.bypass=!1;var h=c?"addEventListener":"removeEventListener";a.core[h]("ImageStreamReady",d);a.core[h]("DrawComplete",b);a.core[h]("BeforeDispose",t);if(c===!0){var l;i.invokeCSS===!0&&g.invoke("print");for(l in a.core.items)e(a.core.items[l]),
e()}else{var p;g.invoke("error");for(p in a.core.items)j.removeCanvasElementOf(a.core.items[p]);i.bypass||a.raiseEvent("PrintReadyStateChange",{ready:!1,bypass:i.bypass});g.invoke("normal")}return i.enabled=c},managedPrint:function(b){i.bypass?window.print():a.core.printManager.isReady()?typeof b==="object"&&b.ready!==!0||(a.removeEventListener("PrintReadyStateChange",a.core.printManager.managedPrint),window.print()):a.core.printManager.enabled(!0)!==!0?window.print():a.addEventListener("PrintReadyStateChange",
a.core.printManager.managedPrint)}}},!1);FusionChartsEvents.PrintReadyStateChange="printreadystatechange"}})();
